# Configuration de l'API AI/ML
# Votre clé API Gemini AI
ai.ml.api.key=AIzaSyCZMq8dcEMnMVxEFAQqSRDCQH1yizjYEcA

# URL de l'API Gemini AI (using TLS)
ai.ml.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent

# Paramètres de base
ai.ml.temperature=0.7
ai.ml.max_tokens=800

# Format de réponse attendu
ai.ml.response_format=json
