<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Exercice extends \App\Entity\Exercice implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'criteres_evaluation' => [parent::class, 'criteres_evaluation', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'fichierPdf' => [parent::class, 'fichierPdf', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'niveauDifficulte' => [parent::class, 'niveauDifficulte', null],
        "\0".parent::class."\0".'noteMinimale' => [parent::class, 'noteMinimale', null],
        "\0".parent::class."\0".'solution' => [parent::class, 'solution', null],
        "\0".parent::class."\0".'tempsEstime' => [parent::class, 'tempsEstime', null],
        "\0".parent::class."\0".'tentatives' => [parent::class, 'tentatives', null],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null],
        "\0".parent::class."\0".'typeExercice' => [parent::class, 'typeExercice', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'criteres_evaluation' => [parent::class, 'criteres_evaluation', null],
        'description' => [parent::class, 'description', null],
        'fichierPdf' => [parent::class, 'fichierPdf', null],
        'id' => [parent::class, 'id', null],
        'niveauDifficulte' => [parent::class, 'niveauDifficulte', null],
        'noteMinimale' => [parent::class, 'noteMinimale', null],
        'solution' => [parent::class, 'solution', null],
        'tempsEstime' => [parent::class, 'tempsEstime', null],
        'tentatives' => [parent::class, 'tentatives', null],
        'titre' => [parent::class, 'titre', null],
        'typeExercice' => [parent::class, 'typeExercice', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
