<?php

namespace Container1yfpwpD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3sh_CE1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3sh.cE1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3sh.cE1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'recommendationService' => ['privates', 'App\\Service\\ExerciceRecommendationService', 'getExerciceRecommendationServiceService', true],
        ], [
            'recommendationService' => 'App\\Service\\ExerciceRecommendationService',
        ]);
    }
}
