<?php

namespace Container1yfpwpD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Rc9zj_OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Rc9zj.o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Rc9zj.o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorieCours' => ['privates', '.errored..service_locator.Rc9zj.o.App\\Entity\\CategorieCours', NULL, 'Cannot autowire service ".service_locator.Rc9zj.o": it needs an instance of "App\\Entity\\CategorieCours" but this type has been excluded in "config/services.yaml".'],
        ], [
            'categorieCours' => 'App\\Entity\\CategorieCours',
        ]);
    }
}
