<?php

namespace Container1yfpwpD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AuMyxEcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AuMyxEc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AuMyxEc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorieCoursRepository' => ['privates', 'App\\Repository\\CategorieCoursRepository', 'getCategorieCoursRepositoryService', true],
            'coursRepository' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService', true],
        ], [
            'categorieCoursRepository' => 'App\\Repository\\CategorieCoursRepository',
            'coursRepository' => 'App\\Repository\\CoursRepository',
        ]);
    }
}
