<?php

namespace Container1yfpwpD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CtAlk7xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CtAlk7x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CtAlk7x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tentativeRepository' => ['privates', 'App\\Repository\\TentativeRepository', 'getTentativeRepositoryService', true],
        ], [
            'tentativeRepository' => 'App\\Repository\\TentativeRepository',
        ]);
    }
}
