<?php

namespace Container1yfpwpD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JDl3qiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J_dl3qi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J_dl3qi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'exerciceRepository' => ['privates', 'App\\Repository\\ExerciceRepository', 'getExerciceRepositoryService', true],
            'tentativeRepository' => ['privates', 'App\\Repository\\TentativeRepository', 'getTentativeRepositoryService', true],
        ], [
            'exerciceRepository' => 'App\\Repository\\ExerciceRepository',
            'tentativeRepository' => 'App\\Repository\\TentativeRepository',
        ]);
    }
}
