<?php

namespace Container1yfpwpD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExerciceRecommendationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\ExerciceRecommendationService' shared autowired service.
     *
     * @return \App\Service\ExerciceRecommendationService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ExerciceRecommendationService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\ExerciceRecommendationService'])) {
            return $container->privates['App\\Service\\ExerciceRecommendationService'];
        }

        return $container->privates['App\\Service\\ExerciceRecommendationService'] = new \App\Service\ExerciceRecommendationService(($container->privates['App\\Repository\\TentativeRepository'] ?? $container->load('getTentativeRepositoryService')), ($container->privates['App\\Repository\\ExerciceRepository'] ?? $container->load('getExerciceRepositoryService')), $a);
    }
}
