<?php

namespace ContainerDv14PBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PvuXIIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pvuX_iI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pvuX_iI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tentative' => ['privates', '.errored..service_locator.pvuX_iI.App\\Entity\\Tentative', NULL, 'Cannot autowire service ".service_locator.pvuX_iI": it needs an instance of "App\\Entity\\Tentative" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'tentative' => 'App\\Entity\\Tentative',
        ]);
    }
}
