<?php

namespace ContainerDv14PBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FJfRovZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fJfRovZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fJfRovZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'exercice' => ['privates', '.errored..service_locator.fJfRovZ.App\\Entity\\Exercice', NULL, 'Cannot autowire service ".service_locator.fJfRovZ": it needs an instance of "App\\Entity\\Exercice" but this type has been excluded in "config/services.yaml".'],
            'pdfService' => ['privates', 'App\\Service\\PdfService', 'getPdfServiceService', true],
        ], [
            'exercice' => 'App\\Entity\\Exercice',
            'pdfService' => 'App\\Service\\PdfService',
        ]);
    }
}
