<?php

namespace ContainerDv14PBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zvz27eMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Zvz27eM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Zvz27eM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorieCoursRepository' => ['privates', 'App\\Repository\\CategorieCoursRepository', 'getCategorieCoursRepositoryService', true],
            'coursRepository' => ['privates', 'App\\Repository\\CoursRepository', 'getCoursRepositoryService', true],
            'exerciceRepository' => ['privates', 'App\\Repository\\ExerciceRepository', 'getExerciceRepositoryService', true],
            'inscriptionRepository' => ['privates', 'App\\Repository\\InscriptionRepository', 'getInscriptionRepositoryService', true],
            'publicationRepository' => ['privates', 'App\\Repository\\PublicationRepository', 'getPublicationRepositoryService', true],
            'tentativeRepository' => ['privates', 'App\\Repository\\TentativeRepository', 'getTentativeRepositoryService', true],
        ], [
            'categorieCoursRepository' => 'App\\Repository\\CategorieCoursRepository',
            'coursRepository' => 'App\\Repository\\CoursRepository',
            'exerciceRepository' => 'App\\Repository\\ExerciceRepository',
            'inscriptionRepository' => 'App\\Repository\\InscriptionRepository',
            'publicationRepository' => 'App\\Repository\\PublicationRepository',
            'tentativeRepository' => 'App\\Repository\\TentativeRepository',
        ]);
    }
}
