<?php

namespace ContainerDv14PBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EanBMHiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EanBMHi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EanBMHi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorieCours' => ['privates', '.errored..service_locator.EanBMHi.App\\Entity\\CategorieCours', NULL, 'Cannot autowire service ".service_locator.EanBMHi": it needs an instance of "App\\Entity\\CategorieCours" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'categorieCours' => 'App\\Entity\\CategorieCours',
            'entityManager' => '?',
        ]);
    }
}
