<?php

namespace ContainerDv14PBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TLLIJ1RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tLLIJ1R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tLLIJ1R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categorieCoursRepository' => ['privates', 'App\\Repository\\CategorieCoursRepository', 'getCategorieCoursRepositoryService', true],
        ], [
            'categorieCoursRepository' => 'App\\Repository\\CategorieCoursRepository',
        ]);
    }
}
