<?php

namespace ContainerDv14PBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieCoursService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EanBMHi.App\Entity\CategorieCours' shared service.
     *
     * @return \App\Entity\CategorieCours
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.EanBMHi": it needs an instance of "App\\Entity\\CategorieCours" but this type has been excluded in "config/services.yaml".');
    }
}
