<?php

namespace ContainerDv14PBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExercice3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.fJfRovZ.App\Entity\Exercice' shared service.
     *
     * @return \App\Entity\Exercice
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.fJfRovZ": it needs an instance of "App\\Entity\\Exercice" but this type has been excluded in "config/services.yaml".');
    }
}
