<?php

namespace ContainerDv14PBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRecommendationControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\RecommendationController' shared autowired service.
     *
     * @return \App\Controller\Api\RecommendationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Api'.\DIRECTORY_SEPARATOR.'RecommendationController.php';

        $container->services['App\\Controller\\Api\\RecommendationController'] = $instance = new \App\Controller\Api\RecommendationController(($container->privates['App\\Service\\ExerciceRecommendationService'] ?? $container->load('getExerciceRecommendationServiceService')), ($container->privates['debug.serializer'] ?? self::getDebug_SerializerService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Api\\RecommendationController', $container));

        return $instance;
    }
}
