<?php

namespace ContainerDv14PBx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTentative2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.pvuX_iI.App\Entity\Tentative' shared service.
     *
     * @return \App\Entity\Tentative
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.pvuX_iI": it needs an instance of "App\\Entity\\Tentative" but this type has been excluded in "config/services.yaml".');
    }
}
